s/𝕊/𝕊_{S}/g
s/⟅/\\lhbracket/g
s/⟆/\\rhbracket/g
s/<|>/\\halt/g
s/>>=/\\bind/g
s/>>/\\skip/g
s/++/\\plus/g
s/<=</\\hkcomp/g
s/=<</\\lbind/g
s/<\\$>/{\\hfmap}/g
s/Type-/Type/g
s/`/\\codetick{}/g
s/'/\\textquotesingle{}/g
