name: Compile LaTeX and HTML
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        cubical-ref: ["a60b0c6576fac0ba6e181cab75f9f9de2d167f87"]
        agda-ver: ["2.6.2"]
        
    steps:

  # Install Agda
    - uses: wenkokke/setup-agda@v2.0.0
      with:
        agda-version: ${{ matrix.agda-ver }}
        agda-stdlib-version: 'recommended'
        agda-libraries: |
          https://github.com/agda/cubical.git#${{ matrix.cubical-ref }}


# Download this git repo
    - name: Checkout main
      uses: actions/checkout@v2
      with:
        path: main

# Download and compile agda code

    - uses: actions/cache@v2
      name: Cache agda code
      id: cache-agda
      with:
        path: ~/main-build
        key: html-and-tex-${{ runner.os }}-${{ matrix.agda-ver }}-${{ matrix.cubical-ref }}-${{ hashFiles('main/agda/**') }}
        restore-keys: |
          html-and-tex-${{ runner.os }}-${{ matrix.agda-ver }}-${{ matrix.cubical-ref }}-
          html-and-tex-${{ runner.os }}-${{ matrix.agda-ver }}-

    - name: Cache hit on agda code; retrieve agda code library
      if: steps.cache-agda.outputs.cache-hit == 'true'
      run: cp -f -R ~/main-build/* $GITHUB_WORKSPACE/main/agda

    - name: Cache miss on agda code; compile Agda code
      if: steps.cache-agda.outputs.cache-hit != 'true'
      run: |
        mkdir -p ~/main-build/_build
        cp -f -R ~/main-build/_build main/agda/_build
        rm -r ~/main-build

        cd main
        ./scripts/generate-everything-agda.sh Everything
        cd agda
        agda --html --html-dir=docs Everything.agda
        rm Everything.agda

        sudo apt-get install texlive-binaries
        find . -type f -name '*.lagda' | while read -r code ; do
            agda --latex --latex-dir=. $code
        done
        cd ..
        cp -f -R agda/ ~/main-build/

# Compile pdf
    - name: Remove .latexmkrc
      run: rm main/.latexmkrc

    - name: Compile latex
      uses: xu-cheng/latex-action@v2
      with:
        working_directory: main
        root_file: paper.tex

    - name: Upload generated pdf
      uses: actions/upload-artifact@v2
      with:
        name: paper
        path: main/paper.pdf

    - name: Make site folder
      run: mkdir site

    - name: Move generated pdf into site folder
      run: mv main/paper.pdf site/paper.pdf

    - name: Move agda html into site folder
      run: mv main/agda/docs site/agda

    - name: Deploy html and pdf to github pages
      uses: peaceiris/actions-gh-pages@v3.7.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: site
        destination_dir: agda-tex
